create table menu
(
	id bigint generated by default as identity
		constraint menu_pkey
			primary key,
	description varchar(255),
	name varchar(255),
	price numeric(19,2),
	restaurant_id bigint
		constraint fkblwdtxevpl4mrds8a12q0ohu6
			references restaurant
);

alter table menu owner to qfood;

