create table location
(
	id bigint generated by default as identity
		constraint location_pkey
			primary key,
	latitude double precision,
	longitude double precision
);

alter table location owner to qfood;

