create table restaurant
(
	id bigint generated by default as identity
		constraint restaurant_pkey
			primary key,
	dataupdatedat timestamp,
	datecreatedat timestamp,
	documentid varchar(255),
	name varchar(255),
	owner varchar(255),
	location_id bigint
		constraint fk8xt7uuc7ola9jk93wl3i43ule
			references location
);


